package:
  name: heliq
  version: "{{ load_setup_py_data().version }}"

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.7
    - setuptools
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - heliq

about:
  home: https://github.com/wohe157/heliq
  doc_url: https://heliq.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: "Quantification of helical morphologies"
